before_install:
 - sudo apt-get update
 - sudo apt-get install rubygems
 - sudo apt-get install jekyll
 - sudo apt-get install nodejs npm
 - sudo apt install nodejs-legacy
 - sudo npm i markdown-spellcheck -g
 - sudo apt-get install hunspell hunspell-fr
language: ruby
# command to run tests
script: ./travis.sh
